### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by prateek2211** [mdg-iitr/codephile-backend#196]
Create a home page for the app (designs are already available)

**Comment by prateek2211** [comment]
https://www.figma.com/file/mdSw0hf8xCb8r7csv4sVM9/Codephile?node-id=1335%3A5051

**Comment by priyangsi** [comment]
This is the landing page (The images used are in the "images" folder within this Codephile folder)
[Codephile.zip](https://github.com/mdg-iitr/codephile-backend/files/6435248/Codephile.zip)

**Comment by prateek2211** [comment]
#213
