### ISSUE TITLE
Use google API for sending emails

### ISSUE THREAD

**Issue by prateek2211** [mdg-iitr/codephile-backend#200]
https://developers.google.com/gmail/api/quickstart/go

**Comment by Saksham-Sharma-99** [comment]
i may be wrong .. but google api for sending email is only for java and python ! isn't it?

**Comment by prateek2211** [comment]
The link which I mentioned has examples for golang

**Comment by prateek2211** [comment]
This file is responsible for sending email: 
https://github.com/mdg-iitr/Codephile/blob/master/services/mail/mail_sender.go

**Comment by silentC1C4D4** [comment]
Can I claim this issue? @prateek2211

**Comment by dev-ritik** [comment]
If @Saksham-Sharma-99 has not already started working on it, you can claim the issue.

**Comment by Saksham-Sharma-99** [comment]
Hi @silentC1C4D4 .. i am already working on it..sorry..could please work on some other issue. Thanks :)

**Comment by silentC1C4D4** [comment]
Yeah, sure thing!
